### ISSUE TITLE
Scrape 2018 observer data

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/af-elections-data#12]
The breakdown of observers per province should be compiled from the multiple sheets in the workbook found here:

https://docs.google.com/spreadsheets/d/1H6T57vHCOJfofok4fMRdQ2ViUbEGmt867N8uyBarpRw/edit?usp=sharing

While the 2018 data story requests only total observers per province, I suggest we add all data points per province for posterity.

**Comment by LanesGood** [comment]
This is now available in CSV. @olafveerman should this be uploaded as a separate file, or merged with the existing province CSV?

[provinces-observers.csv.zip](https://github.com/developmentseed/af-elections-data/files/3049506/provinces-observers.csv.zip)

**Comment by olafveerman** [comment]
@LanesGood In future, please open PRs to `master` so we can review.

Things to do:

1. document the source of the data and the meaning of the ambiguous columns in a Readme. I think we should do this for every year and have opened a ticket to track #15 
2. remove `geoId`, this will be tracked in `provinces.csv`
3. better column names (no spaces, no typos, consistent syntax). Eg. `observersTotal`, `observersFemle`, `pollingStationsMale`

**Comment by LanesGood** [comment]
@olafveerman OK, I've added the Readme and replaced this file in a new branch
