### ISSUE TITLE
Review 2014 geoId

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/af-elections-data#18]
The `geoId` columns of the 2014 provinces and districts should be verified. These files are currently part of this PR, but should soon be on `master`: https://github.com/developmentseed/af-elections-data/pull/16

According to the documentation, the `geoId` column follows one of the `agcho` standards. Check if they match the `421 CSO` that we settled on as our default.

**Comment by Rub21** [comment]
@olafveerman  We update the geoId in the districts.csv file in  `2014-presidential-runoff` and `2014-presidential-firstround` folders.

Some of the Ids in the file was `0` , we fixed that as well.

e.g:
<img width="766" alt="Screen Shot 2019-04-12 at 10 56 17 AM" src="https://user-images.githubusercontent.com/1152236/56050475-a7a5d100-5d11-11e9-9516-5b27440669f7.png">

https://github.com/developmentseed/af-elections-data/pull/30/files#diff-ded0a8b5e0e0939f98a1137229f4dcc8L124 
https://github.com/developmentseed/af-elections-data/pull/30/files#diff-ded0a8b5e0e0939f98a1137229f4dcc8L271

And  this group of districts does not have the `provId` 


id | name | provId | geoId
-- | -- | -- | --
1312 | Laja Mangal |   | 1312
808 | Abshar |   | 808
2718 | Takhta Pul |   | 2718
2717 | Dand |   | 907
2506 | Chenarto |   | 2507
1313 | Meerzaka |   | 1313
3014 | Marja |   | 3014
3406 | Delaram |   | 3406

PR: https://github.com/developmentseed/af-elections-data/pull/30

**Comment by Rub21** [comment]
Closing this ticket the PR was merged!
