### ISSUE TITLE
Review and add geoID to 2010 data

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/af-elections-data#2]
- review the geoId of the provinces and make sure we are using 
- add the geoId to the districts

We should be using the `419 AGCHO` standard.

**Comment by olafveerman** [comment]
This list can be used as a reference: https://docs.google.com/spreadsheets/d/1Qa1Fhj2UB-Iwsl0W24vaGmQsbbIGK3RTFl94Zv7pId4/edit#gid=102916203

**Comment by Rub21** [comment]
@olafveerman here is the updated district.csv file : https://github.com/developmentseed/af-elections-data/blob/fix-districs/2010-wolesi-jirga/districts.csv

Most of the work was done manually, in many cases, the names are not equal. also, there were some of the districts we could not find. 


138 | Province Center(MARKAZ-WOLLAYAT) | 32 |  
-- | -- | -- | --
152 | DAIKONDI | 34 |  
149 | HESSA-E-AWAL | 33 |  
221 | CHIPERHAR | 10 | NA
68 | Provincial Center (Nooristan) | 13 |  


here the spreadsheet when we fill the geoId: https://docs.google.com/spreadsheets/d/1OM2MbCUOmQodBETdGZBGTHzVX8FVpD9u40X9r0f7_RM/edit#gid=297741507

**Comment by olafveerman** [comment]
Thanks, we can leave these without `geoId` for the moment.
Keeping this ticket open so it's still on our radar.

**Comment by Rub21** [comment]
I found the missing ids, thanks to @LanesGood  on : https://github.com/developmentseed/aodp-data/blob/master/data/af_data/districts_rosetta_stone.csv#L282

some of the geoIds are the same, but some differents from the old data:  👇 

Distric| Province |[districts_rosetta_stone](https://github.com/developmentseed/aodp-data/blob/master/data/af_data/districts_rosetta_stone.csv#L282) | `419 AGCHO`
---|----|---|----
Province Center(MARKAZ-WOLLAYAT)| Bamyan | 1001 | 1001
HESSA-E-AWAL | Panjshir | 0805 | 0805
CHIPERHAR | Nangerhar | 0605 | 0605
Provincial Center (Nooristan) | Nooristan | 1401 | **1601** (Currently the province id start with `16`)
DAIKONDI | DAIKONDI | 2201 | **2401**  (Currently the province id start with `24`)


I have added the messing district geoId form  `419 AGCHO`  column in the district.csv

https://github.com/developmentseed/af-elections-data/pull/9/files

**Comment by olafveerman** [comment]
Great, thanks @Rub21  and @LanesGood . Fixed, closing this issue.
