### ISSUE TITLE
Add Kuchi and Sikh metadata to their provinces

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/af-elections-data#48]
Currently, Kuchi and Sikh metadata like `registeredVoters` are included in [the actual provinces](https://github.com/developmentseed/af-elections-data/blob/master/2018-wolesi-jirga/provinces-registered-voters.csv) (Kabul, Kapisa, etc).

| id | name | registeredMen | registeredWomen | registeredNomad | registeredHinduSikh | registeredTotal |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | KABUL | 1041185 | 522214 | 68039 | 759 | 1632197 |

Since the IEC vote count for Kuchi and Sikh are reported in separate and special provinces, their metadata should follow the same logic. If we don't, voter participation rates will be off (eg. Total votes Kabul / Registered voters Kabul).

**Comment by olafveerman** [comment]
Thanks @LanesGood , this is great for quick prototyping.

To produce the final insights and maps, let's make sure we're using the data in this repository. That way we have a clearer audit trail of where the data is coming from.

**Comment by olafveerman** [comment]
Wait... are we in the future now?

![image](https://user-images.githubusercontent.com/751330/57385665-da13e400-7180-11e9-88a3-4153dd4b5869.png)

**Comment by LanesGood** [comment]
I have also done this in the google sheet - the new registeredTotal-2 column is a sum of Men + Women. The Kuchi and Sikh voters are then totaled in their respective provinces
[AF-2018WJ-DataStoriesMaster](https://docs.google.com/spreadsheets/d/1jctcTPwJ6MP-NWBX6u5DtrNJB6dAuL1eu6c-E1Q9rok/edit?usp=sharing)
