### ISSUE TITLE
Add incumbent to candidates.csv

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/af-elections-data#6]
Based on the 2010 election results, determine which candidates are incumbent in 2018.

**Comment by olafveerman** [comment]
See this comment with a link to all the current parliamentarians: https://github.com/developmentseed/af-elections/issues/90#issuecomment-480083710
We should use that link to determine if somebody's an incumbent.

**Comment by Rub21** [comment]
@olafveerman  for better understanding, there are some candidates according to the PDF which were incumbent in 2010-2015 👇 
![Screen Shot 2019-04-05 at 4 19 48 PM](https://user-images.githubusercontent.com/1152236/55657200-112c5980-57bf-11e9-879e-4b4239d8deb2.png)


If some of these candidates appear in the `candidates.csv` 2018 file we should set them `incumbent=yes` , am I right?

**Comment by Rub21** [comment]
@olafveerman  we found only few incumbent  candidates : 👇 

name | ballotNumber | gender | party | incumbent
-- | -- | -- | -- | --
Dr. Ramazan Bashardost | 788 | M | Ind | yes
Shah Gull Rezaye | 337 | F | Ind | yes
Mohammad Noor Akbari | 21 | M | Political party | yes
Khalid Pashton | 13 | M | Ind | yes
Mirwais Yasini | 71 | M | Ind | yes
Saaima Khogyani | 32 | F | Ind | yes


we have added them in the PR: https://github.com/developmentseed/af-elections-data/pulls
And there a few differences in two candidates: 

candidates.csv | pdf file
---|---
Saaima Khogyani | Saima Khogyani											
Dr. Ramazan Bashardost | Dr. Ramazan Bashar Dost	

We cosidered them as the same person.

**Comment by olafveerman** [comment]
@Rub21 All the candidates listed on this page can be considered 'incumbent':

http://wolesi.website/pve/page.aspx?Cat=101

**Comment by Rub21** [comment]
@olafveerman  from the above list we found around 50 candidates as incumbent 

Most of the names are the same: https://gist.github.com/Rub21/4841ffe79588bd8b78f869d95b631116 : but these names 👇  differ a litle bit. 


id | name | candidate from web-list | ballotNumber | gender | party | incumbent
-- | -- | -- | -- | -- | -- | --
1-1325-39 | Abdul Hafiz Mansoor | Abdul Hafiz Mansor | 165 | M | Ind | TRUE
27-1299-5 | Attaullah Jaan Habib | Attaullah Jan Habib | 30 | M | Ind | TRUE
27-1225-1 | Bibi Hamida Yousufi | Bi Bi Hamida Yousufi | 71 | F | Ind | TRUE
29-1537-2039 | Fathullah Qaisari | Fatehullah Qaisari | 8 | M | Ind | TRUE
17-1169-15 | Fazel Azim Zalmai Mujadedi | Fazel Azim Zalmai Mujadidi | 69 | M | Ind | TRUE
32-1161-6 | Ghullam Farooq Majroh | Ghulam Farooq Majroh | 92 | M | Ind | TRUE
21-1637-15 | Gull Mohammad Pahlawan | Gul Mohammad Pahlawan | 69 | M | Ind | TRUE
21-1081-80 | **Dr Gullalai Noor Safi** | Gulalai Noor Safi | 63 | F | Ind | TRUE
23-1605-59 | Keramuddin Rezazadah | Keramuddin Reza Zada | 19 | M | Ind | TRUE
32-1665-1086 | Haji Khalil Ahmad Shahidzada | Khalil Ahmad Shahidzada | 66 | M | Ind | TRUE
20-1418-1 | Makhdom Abdalullah Mohammadi | Makhdom Abdallulah Mohammadi | 23 | M | Ind | TRUE
14-1093-37 | **Dr Mirbat Khan Mangal** | Mir Bat Khan Mangal | 8 | M | Ind | TRUE
2-1249-103 | Mirdaad Khan Nejrabi | Mir Dad Khan Nejrabi | 34 | M | Ind | TRUE
1-1443-91 | Haji Mohammad Farhad Sediqi | Mohammad Farhad Sediqi | 106 | M | Ind | TRUE
1-1838-192 | Mohammad Hassan Mamozai | Mohammad Hassan Mamozay | 66 | M | Ind | TRUE
22-1141-40 | Mohammad Hussain Fahimi | Mohammad Hussan Fahimi | 7 | M | Political party | TRUE
32-1381-1049 | **Dr Mohammad Saleh Saljoqi** | Mohammad Saleh Saljoqi | 160 | M | Ind | TRUE
32-1078-1064 | Rahima Jaami | Rahima Jami | 45 | F | Ind | TRUE
1-1305-89 | **Dr. Ramazan Bashardost** | Ramazan Bashardost | 788 | M | Ind | TRUE
13-1542-1075 | Razia Saadat Mangal | Razia Sadat Mangal | 30 | F | Ind | TRUE
1-1450-1083 | Shah Gull Rezaye | Shah Gul Rezaye | 337 | F | Ind | TRUE


In cases od **DR** prefix I think it woould be ok, but in some other i want  to confirm with you: https://github.com/developmentseed/af-elections-data/pull/13

**Comment by Rub21** [comment]
The [branch](https://github.com/developmentseed/af-elections-data/pull/13) was merged, looks the list is ok, closing this ticket!
