### ISSUE TITLE
Review population district 2018 data

### ISSUE THREAD

**Issue by Rub21** [developmentseed/af-elections-data#62]
The districtx population data for some districts are  is repeated: 
[dist.json.zip](https://github.com/developmentseed/af-elections-data/files/3192954/dist.json.zip)
https://github.com/developmentseed/af-elections-data/blob/master/2018-wolesi-jirga/districts.csv
example:

```
 "name": "Provincial Capital Of Herat (herat)",
        "name_dari": "هرات",
        "id": 320101,
        "dist_id": 3201,
        "province_name": "Hirat",
        "province_name_dari": "هرات",
        "province_id": 32,
        "admin_type": "district",
        "unit_type": "District",
        "distId": 320101,
        "provId": 32,
        "geoId": 3201,
        "registeredMen": 6611,
        "registeredWomen": 4660,
        "registeredTotal": 11271,
        "femalePopulationRural": 0,
        "malePopulationRural": 0,
        "totalPopulationRural": 0,
        "femalePopulationUrban": 270069,
        "malePopulationUrban": 268604,
        "totalPopulationUrban": 538673,
        "totalPopulationFemale": 270069,
        "totalPopulationMale": 268604,
        "totalPopulation": 270069,
        "womenCandidates": 28,
```

From ☝️  the `totalPopulation`  and `totalPopulationFemale` has the same values, coudl you check it.

cc. @karitotp @LanesGood

**Comment by karitotp** [comment]
Yes, as mentioned in # 63, the previous total population came from totalPopulationRural + totalPopulationFemale.
Closing this, because it was already fixed by Lane.
