### ISSUE TITLE
Add 2019 invalidated/closed PC/PS data

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/af-elections-data#76]
Data from http://www.iec.org.af/results/en/invalid/invalid_by_pc should be scraped and added to this repo for site usage.

**Comment by vgeorge** [comment]
Raw data from all provinces was scraped and added to this sheet:

https://docs.google.com/spreadsheets/d/1uvxr2z2HsFZk3hOfNmA9DARJYhb58ooWI48e34p8dNM/edit?usp=sharing

Each tab contain one or more pages for each province. The remaining tasks are:

- [ ] Add provinceId column to each sheet
- [ ] Merge all sheets into one
- [ ] Include pcId column by splitting "Polling Center" column

**Comment by vgeorge** [comment]
@LanesGood Now you can see the results per PC in one sheet and also aggregated by province. Can you please review? If they are ok I'll add to the repo as a CSV file.

**Comment by LanesGood** [comment]
@vgeorge this is excellent! For data tracking purposes I'd suggest that we also split the "Polling Station" column into Station # and gender. This will allow us to then easily create a helper column to do a join with the other polling station data, which can make the "# of closed/invalid stations" and "# votes discarded" stat calculations more traceable. I'll go ahead and split this out, and then this can be added as a CSV file.

**Comment by vgeorge** [comment]
The file was added and can be found here:

https://github.com/developmentseed/af-elections-data/blob/master/2019-presidential-firstround/complementary/pc-ps-invalidated-closed.csv
